ProyectoInfo/urls.py
from django.contrib import admin
from django.urls import path, include
from usuario.views import registro, login, logout, home

urlpatterns = [
    path('admin/', admin.site.urls),
    path('juego/', include('juego.urls')),
    path('registro',registro),
    path('login',login),
    path('logout',logout),
    path('',home),
]

juego/urls.py
from django.urls import path
from . import views

app_name ="juego"
urlpatterns = [
    path('', views.listar_preguntas, name='listar_preguntas'),
    path('preguntas', views.preguntas, name="preguntas"),
    path("detalle_pregunta/<int:identificador>", views.detalle_pregunta, name="detalle_pregunta"),
    path('crear', views.crear_pregunta, name="crear_pregunta"),
    path("editar_pregunta/<int:identificador>", views.editar_pregunta, name="editar"),
    path('eliminar/<int:identificador>', views.eliminar_pregunta, name="eliminar"),
    path('confirmar_eliminacion/<int:identificador>', views.confirmar_eliminacion, name="confirmar_eliminacion"),
    path('respuestas', views.respuestas, name="respuestas"),
    path("detalle_respuesta/<int:identificador>", views.detalle_respuesta, name="detalle_respuesta"),
    path('crear_respuesta', views.crear_respuesta, name="crear_respuesta"),
    path("editar_respuesta/<int:identificador>", views.editar_respuesta, name="editar_respuesta"),
    path('eliminar_respuesta/<int:identificador>', views.eliminar_respuesta, name="eliminar_respuesta"),
    path('confirmar_eliminacionn/<int:identificador>', views.confirmar_eliminacionn, name="confirmar_eliminacionn"),
    path('categorias', views.categorias, name="categorias"),
    path("detalle_categoria/<int:identificador>", views.detalle_categoria, name="detalle_categoria"),
    path('crear_categoria', views.crear_categoria, name="crear_categoria"),
    path("editar_categoria/<int:identificador>", views.editar_categoria, name="editar_categoria"),
    path('eliminar_categoria/<int:identificador>', views.eliminar_categoria, name="eliminar_categoria"),
    path('confirmar_eliminaciion/<int:identificador>', views.confirmar_eliminaciion, name="confirmar_eliminaciion"),
    path('pagina',views.pagina),
    path('noticias',views.noticias),
    path('partidas',views.partidas, name="partidas"),
]

juego/models.py
from django.db import models

# Create your models here.
from django.db import models

class Pregunta(models.Model):
    autor = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    pregunta= models.CharField(max_length=200)
    fecha_creacion = models.DateTimeField(auto_now_add=True)
    id_categoria = models.ForeignKey('Categoria', on_delete=models.CASCADE)

    def __str__(self):
        return self.pregunta


class Respuesta(models.Model):
    id_pregunta= models.ForeignKey('Pregunta', on_delete=models.CASCADE)
    opcion= models.CharField(max_length=200)
    puntaje= models.IntegerField()

    def __str__(self):
        return self.opcion

class Partida(models.Model):
    usuario = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    fecha = models.DateTimeField(auto_now_add=True)
    resultado= models.IntegerField()


class Categoria(models.Model):
    categoria= models.CharField(max_length=100)
    descripcion= models.CharField(max_length=800)

    def __str__(self):
        return self.categoria

juego/forms.py
from django import forms
from .models import Pregunta
from .models import Respuesta
from .models import Categoria

class PreguntaForm(forms.ModelForm):

    class Meta:
        model = Pregunta
        fields = ('pregunta','id_categoria')

class RespuestaForm(forms.ModelForm):

    class Meta:
        model = Respuesta
        fields = ('opcion','puntaje','id_pregunta')

class CategoriaForm(forms.ModelForm):

    class Meta:
        model = Categoria
        fields = ('categoria','descripcion')

juego/views.py
# Create your views here.
from django.shortcuts import render, redirect
from .models import Pregunta, Respuesta, Partida
from datetime import datetime

from django.contrib.auth.decorators import login_required
from .models import Categoria
# Create your views here.
@login_required(login_url='/login')
def listar_preguntas(request):
    if request.method == "POST":
        resultado = 0
        for i in range(1, 10):
            opcion = Respuesta.objects.get(pk=request.POST[str(i)])
            resultado += opcion.puntaje
        Partida.objects.create(usuario=request.user, fecha=datetime.now, resultado=resultado)
        return redirect("/juego/partidas")
    else:
        data = {}
        preguntas = Pregunta.objects.all().order_by('?')[:10]
        for item in preguntas:
            respuestas = Respuesta.objects.filter(id_pregunta= item.id)
            categoria = Categoria.objects.get(pk=item.id_categoria.id)
            #{pregunta: {opciones: [opcion1, opcion2, opcionn], categoria: categoria}
            data[item.pregunta]= {'opciones': respuestas, 'categoria': categoria}
        return render(request, 'juego/listar_preguntas.html', {"preguntas": preguntas, "data": data})


@login_required(login_url='/login')
def crear_pregunta(request):
    form = PreguntaForm()
    return render(request, 'juego/crear_pregunta.html', {'form': form})

from django.contrib.auth.decorators import permission_required
@login_required(login_url='/login')
@permission_required('juedo.views_pregunta', login_url='/login')
def preguntas(request):
    preguntas= Pregunta.objects.all()
    return render(request, 'juego/preguntas.html', {"preguntas": preguntas})

@permission_required('juedo.views_pregunta', login_url='/login')
@login_required(login_url='/login')
def detalle_pregunta(request, identificador):
    pregunta = Pregunta.objects.get(pk=identificador)
    return render(request, 'juego/detalle_pregunta.html', {"pregunta": pregunta})

from .forms import PreguntaForm
from django.contrib.auth.decorators import permission_required

@login_required(login_url='/login')
@permission_required('juedo.add_pregunta', login_url='/login')
def crear_pregunta(request):
    form = PreguntaForm()
    if request.method == "POST":
        form = PreguntaForm(request.POST)
        if form.is_valid():
            registro = form.save(commit=False)
            registro.autor = request.user
            registro.fecha_creacion = datetime.now()
            registro.save()
            return redirect('juego:preguntas')
    return render(request, 'juego/crear_pregunta.html', {'form': form})

@permission_required('juedo.change_pregunta', login_url='/login')
@login_required(login_url='/login')
def editar_pregunta(request, identificador):
    pregunta= Pregunta.objects.get(pk=identificador)
    if request.method == "POST":
        form = PreguntaForm(request.POST, instance=pregunta)
        if form.is_valid():
            item = form.save(commit=False)
            item.autor = request.user
            item.fecha_creacion = datetime.now()
            item.save()
            return redirect('juego:detalle_pregunta', identificador=item.id)
    else:
        form = PreguntaForm(instance=pregunta)
    return render(request, 'juego/editar_pregunta.html', {'form': form})

@permission_required('juedo.delete_pregunta', login_url='/login')
@login_required(login_url='/login')
def eliminar_pregunta(request, identificador):
    pregunta = Pregunta.objects.get(pk=identificador)
    return render(request, 'juego/eliminar_pregunta.html', {"pregunta": pregunta})


@login_required(login_url='/login')
def confirmar_eliminacion(request, identificador):
    Pregunta.objects.get(pk=identificador).delete()
    return redirect("juego:preguntas")

@permission_required('juedo.add_respuesta', login_url='/login')
@login_required(login_url='/login')
def crear_respuesta(request):
    form = RespuestaForm()
    return render(request, 'juego/crear_respuesta.html', {'form': form})

from django.contrib.auth.decorators import permission_required
@login_required(login_url='/login')
@permission_required('juedo.views_respuestas', login_url='/login')
def respuestas(request):
    respuestas= Respuesta.objects.all()
    return render(request, 'juego/respuestas.html', {"respuestas": respuestas})

from django.contrib.auth.decorators import permission_required
@permission_required('juedo.views_respuestas', login_url='/login')
@login_required(login_url='/login')
def detalle_respuesta(request, identificador):
    respuesta = Respuesta.objects.get(pk=identificador)
    return render(request, 'juego/detalle_respuesta.html', {"respuesta": respuesta})

from .forms import RespuestaForm
from django.contrib.auth.decorators import permission_required

@login_required(login_url='/login')
@permission_required('juedo.add_respuesta', login_url='/login')
def crear_respuesta(request):
    form = RespuestaForm()
    if request.method == "POST":
        form = RespuestaForm(request.POST)
        if form.is_valid():
            registro = form.save(commit=False)
            registro.autor = request.user
            registro.fecha_creacion = datetime.now()
            registro.save()
            return redirect('juego:respuestas')
    return render(request, 'juego/crear_respuesta.html', {'form': form})

@permission_required('juedo.change_respuesta', login_url='/login')
@login_required(login_url='/login')
def editar_respuesta(request, identificador):
    respuesta= Respuesta.objects.get(pk=identificador)
    if request.method == "POST":
        form = RespuestaForm(request.POST, instance=respuesta)
        if form.is_valid():
            item = form.save(commit=False)
            item.autor = request.user
            item.fecha_creacion = datetime.now()
            item.save()
            return redirect('juego:detalle_respuesta', identificador=item.id)
    else:
        form = RespuestaForm(instance=respuesta)
    return render(request, 'juego/editar_respuesta.html', {'form': form})

@permission_required('juedo.delete_respuesta', login_url='/login')
@login_required(login_url='/login')
def eliminar_respuesta(request, identificador):
    respuesta = Respuesta.objects.get(pk=identificador)
    return render(request, 'juego/eliminar_respuesta.html', {"respuesta": respuesta})


@login_required(login_url='/login')
def confirmar_eliminacionn(request, identificador):
    Respuesta.objects.get(pk=identificador).delete()
    return redirect("juego:respuestas")

@permission_required('juedo.add_categoria', login_url='/login')
@login_required(login_url='/login')
def crear_categoria(request):
    form = CategoriaForm()
    return render(request, 'juego/crear_categoria.html', {'form': form})

from django.contrib.auth.decorators import permission_required
@login_required(login_url='/login')
@permission_required('juedo.views_categoria', login_url='/login')
def categorias(request):
    categorias= Categoria.objects.all()
    return render(request, 'juego/categorias.html', {"categorias": categorias})

from django.contrib.auth.decorators import permission_required
@permission_required('juedo.views_categoria', login_url='/login')
@login_required(login_url='/login')
def detalle_categoria(request, identificador):
    categoria = Categoria.objects.get(pk=identificador)
    return render(request, 'juego/detalle_categoria.html', {"categoria": categoria})

from .forms import CategoriaForm
from django.contrib.auth.decorators import permission_required

@login_required(login_url='/login')
@permission_required('juedo.add_categoria', login_url='/login')
def crear_categoria(request):
    form = CategoriaForm()
    if request.method == "POST":
        form = CategoriaForm(request.POST)
        if form.is_valid():
            registro = form.save(commit=False)
            registro.autor = request.user
            registro.fecha_creacion = datetime.now()
            registro.save()
            return redirect('juego:categoria')
    return render(request, 'juego/crear_categoria.html', {'form': form})

@permission_required('juedo.change_categoria', login_url='/login')
@login_required(login_url='/login')
def editar_categoria(request, identificador):
    categoria= Categoria.objects.get(pk=identificador)
    if request.method == "POST":
        form = CategoriaForm(request.POST, instance=categoria)
        if form.is_valid():
            item = form.save(commit=False)
            item.autor = request.user
            item.fecha_creacion = datetime.now()
            item.save()
            return redirect('juego:detalle_categoria', identificador=item.id)
    else:
        form = CategoriaForm(instance=categoria)
    return render(request, 'juego/editar_categoria.html', {'form': form})

@permission_required('juedo.delete_categoria', login_url='/login')
@login_required(login_url='/login')
def eliminar_categoria(request, identificador):
    categoria = Categoria.objects.get(pk=identificador)
    return render(request, 'juego/eliminar_categoria.html', {"categoria": categoria})


@login_required(login_url='/login')
def confirmar_eliminaciion(request, identificador):
    Categoria.objects.get(pk=identificador).delete()
    return redirect("juego:categoria")

def pagina(request):
    return render(request, 'juego/pagina.html')

def noticias(request):
    return render(request, "juego/noticias.html")

@login_required(login_url='/login')
def partidas(request):
    partidas = Partida.objects.all().order_by('-fecha')[:5]
    return render(request, "juego/partidas.html", {"partidas": partidas})

templates/juego/categorias.html
<html>
    <head>
        <title>Categorias</title>
    </head>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js" integrity="sha384-eMNCOe7tC1doHpGoWe/6oMVemdAVTMs2xqW4mwXrXsW0L84Iytr2wi5v2QjrP/xp" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.min.js" integrity="sha384-cn7l7gDp0eyniUwwAZgrzD06kc/tftFf19TOAs2zVinnD/C7E91j9yyk5//jjpt/" crossorigin="anonymous"></script>

<body>
<style>body {
  background-image: url(../static/trabajo.jpg);
  background-repeat: no-repeat;
  background-attachment: fixed;
  background-size: cover;
}
</style>
<nav class="navbar navbar-dark bg-primary p-1">
    <ul class="nav justify-content-end">
  <li class="nav-item">
    <a class="nav-link active text-white h4"  aria-current="page" href="/">Pagina Principal</a>
  </li>
  <li class="nav-item">
    <a class="nav-link text-white h4" href="/juego/crear_categoria">Crear Categorias</a>
  </li>
   <li class="nav-item">
    <a class="nav-link text-white h4" href="/juego/preguntas">Listado de Preguntas</a>
  </li>
   <li class="nav-item">
    <a class="nav-link text-white h4" href="/juego/respuestas">Listado de Respuestas</a>
  </li>
</ul>
    <ul class="nav justify-content_end">
    <li class="nav-item" float="right">
    <img src="../static/2logochaco.png" alt="2logochaco.png" width="105" height="75" >
  </li>
</nav>
<p class="h1 m-3" align="center">Listado de Categorias</p>
{% block body %}
    <div class="row justify-content-md-center m-5">
        <div class="mb-3 col-lg-6">
                {% for categoria in categorias %}
                 <div class="alert alert-primary" role="alert">
                     {{categoria}}
                <a class="btn btn-primary" href="{% url 'juego:detalle_categoria' categoria.pk %}">Detalle</a>
                <a class="btn btn-danger" href="{% url 'juego:eliminar_categoria' categoria.pk %}">Eliminar</a>
                     <a class="btn btn-warning" href="{% url 'juego:editar_categoria' categoria.pk %}">Editar</a>
                 </div>
                {% endfor %}
        </div>
     </div>
<div align="center"><a class="btn btn-success" href="/admin">Admin Django</a></div>
{% endblock %}

templates/juego/detalle_pregunta.html
<html>
    <head>
        <title>Detalle</title>
    </head>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js" integrity="sha384-eMNCOe7tC1doHpGoWe/6oMVemdAVTMs2xqW4mwXrXsW0L84Iytr2wi5v2QjrP/xp" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.min.js" integrity="sha384-cn7l7gDp0eyniUwwAZgrzD06kc/tftFf19TOAs2zVinnD/C7E91j9yyk5//jjpt/" crossorigin="anonymous"></script>

<body>
<style>body {
  background-image: url(../static/trabajo.jpg);
  background-repeat: no-repeat;
  background-attachment: fixed;
  background-size: cover;
}
</style>
<nav class="navbar navbar-dark bg-primary p-1">
    <ul class="nav justify-content-end">
  <li class="nav-item">
    <a class="nav-link active text-white h4"  aria-current="page" href="/juego/preguntas">Preguntas</a>
  </li>
  <li class="nav-item">
    <a class="nav-link text-white h4" href="/juego/crear">Crear Preguntas</a>
  </li>
</ul>
</nav>
<p class="h1 m-3" align="center">Detalles de Preguntas</p><br>
{% block body %}
<p class="h5 m-1">Autor : {{pregunta.autor}}</p>
    <br>
<p class="h5 m-1">Pregunta :  {{pregunta.pregunta}}</p>
    <br>
<p class="h5 m-1">Fecha de Creación :  {{pregunta.fecha_creacion}}</p>
    <br>
<p class="h5 m-1">Categoria :  {{pregunta.id_categoria}}</p>

<div align="center"><a class="btn btn-warning" href="{% url 'juego:editar' pregunta.pk %}">Editar</a></div>
{% endblock %}

templates/juego/detalle_respuesta.html
<html>
    <head>
        <title>Detalle Respuesta</title>
    </head>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js" integrity="sha384-eMNCOe7tC1doHpGoWe/6oMVemdAVTMs2xqW4mwXrXsW0L84Iytr2wi5v2QjrP/xp" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.min.js" integrity="sha384-cn7l7gDp0eyniUwwAZgrzD06kc/tftFf19TOAs2zVinnD/C7E91j9yyk5//jjpt/" crossorigin="anonymous"></script>

<body>
<nav class="navbar navbar-dark bg-primary p-1">
    <ul class="nav justify-content-end">
  <li class="nav-item">
    <a class="nav-link active text-white h4"  aria-current="page" href="/juego/respuestas">Respuestas</a>
  </li>
  <li class="nav-item">
    <a class="nav-link text-white h4" href="/juego/crear">Crear Preguntas</a>
  </li>
  <li class="nav-item">
    <a class="nav-link text-white h4" href="/">Pagina Principal</a>
  </li>
</ul>
</nav>
<p class="h1 m-3" align="center">Detalles de Respuestas</p>
{% block body %}
<p class="h5 m-1">Respuesta: {{respuesta.opcion}}</p>
    <br>
<p class="h5 m-1">Pregunta :  {{respuesta.id_pregunta}}</p>
    <br>
<p class="h5 m-1">Puntuaje :  {{respuesta.puntaje}}</p>

<div align="center"><a class="btn btn-warning" href="{% url 'juego:editar_respuesta' respuesta.pk %}">Editar</a></div>
{% endblock %}

templates/juego/eliminar_categoria.html
<html>
    <head>
        <title>Eliminar Categoria</title>
    </head>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js" integrity="sha384-eMNCOe7tC1doHpGoWe/6oMVemdAVTMs2xqW4mwXrXsW0L84Iytr2wi5v2QjrP/xp" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.min.js" integrity="sha384-cn7l7gDp0eyniUwwAZgrzD06kc/tftFf19TOAs2zVinnD/C7E91j9yyk5//jjpt/" crossorigin="anonymous"></script>

<body>
<style>body {
  background-image: url(../static/trabajo.jpg);
  background-repeat: no-repeat;
  background-attachment: fixed;
  background-size: cover;
}
</style>
<nav class="navbar navbar-dark bg-primary p-1">
    <ul class="nav justify-content-end">
  <li class="nav-item">
    <a class="nav-link active text-white h4"  aria-current="page" href="/">Pagina Principal</a>
  </li>
  <li class="nav-item">
    <a class="nav-link active text-white h4"  aria-current="page" href="/juego/respuestas">Lista de Respuestas</a>
  </li>
   <li class="nav-item">
    <a class="nav-link active text-white h4"  aria-current="page" href="/juego/preguntas">Lista de Preguntas</a>
  </li>
</ul>
</nav>
<p class="h1 m-3" align="center">Eliminar Categoria</p>

{% block body %}
<h2>Detalle de Categoria a eliminar</h2><br>
<p class="h5 m-1">Categoria: {{categoria.categoria}}</p>
    <br>
<p class="h5 m-1">Descripcion : {{categoria.descripcion}}</p>

<a class="btn btn-danger" href="{% url 'juego:detalle_categoria' categoria.pk %}">Cancelar</a>
<a class="btn btn-success" href="{% url 'juego:confirmar_eliminaciion' categoria.pk %}">Confirmar</a>

{% endblock %}

templates/juego/eliminar_pregunta.html
<html>
    <head>
        <title>Eliminar</title>
    </head>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js" integrity="sha384-eMNCOe7tC1doHpGoWe/6oMVemdAVTMs2xqW4mwXrXsW0L84Iytr2wi5v2QjrP/xp" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.min.js" integrity="sha384-cn7l7gDp0eyniUwwAZgrzD06kc/tftFf19TOAs2zVinnD/C7E91j9yyk5//jjpt/" crossorigin="anonymous"></script>

<body>
<style> body {
  background-image: url(../static/trabajo.jpg);
  background-repeat: no-repeat;
  background-attachment: fixed;
  background-size: cover;
}
</style>
<nav class="navbar navbar-dark bg-primary p-1">
    <ul class="nav justify-content-end">
  <li class="nav-item">
    <a class="nav-link active text-white h4"  aria-current="page" href="/">Pagina Principal</a>
  </li>
  <li class="nav-item">
    <a class="nav-link text-white h4" href="/juego/crear">Crear Preguntas</a>
  </li>
  <li class="nav-item">
    <a class="nav-link active text-white h4"  aria-current="page" href="/juego/preguntas">Lista de Preguntas</a>
  </li>
</ul>
</nav>
<p class="h1 m-3" align="center">Eliminar Pregunta</p>

{% block body %}
    <h2>Detalle de pregunta a eliminar</h2><br>
<p class="h5 m-1">Autor : {{pregunta.autor}}</p>
    <br>
<p class="h5 m-1">Pregunta :  {{pregunta.pregunta}}</p>
    <br>
<p class="h5 m-1">Fecha de Creación :  {{pregunta.fecha_creacion}}</p>
    <br>
<p class="h5 m-1">Categoria :  {{pregunta.id_categoria}}</p>

<div align="center"><a class="btn btn-danger" href="{% url 'juego:detalle_pregunta' pregunta.pk %}">Cancelar</a></div>
<div align="center"><a class="btn btn-success" href="{% url 'juego:confirmar_eliminacion' pregunta.pk %}">Confirmar</a></div>

{% endblock %}

templates/juego/preguntas.html
<html>
    <head>
        <title>Vista de Preguntas</title>
    </head>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js" integrity="sha384-eMNCOe7tC1doHpGoWe/6oMVemdAVTMs2xqW4mwXrXsW0L84Iytr2wi5v2QjrP/xp" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.min.js" integrity="sha384-cn7l7gDp0eyniUwwAZgrzD06kc/tftFf19TOAs2zVinnD/C7E91j9yyk5//jjpt/" crossorigin="anonymous"></script>

<body>
<style>body {
  background-image: url(../static/trabajo.jpg);
  background-repeat: no-repeat;
  background-attachment: fixed;
  background-size: cover;
}
</style>
<nav class="navbar navbar-dark bg-primary p-1">
    <ul class="nav justify-content-end">
  <li class="nav-item">
    <a class="nav-link active text-white h4"  aria-current="page" href="/">Pagina Principal</a>
  </li>
  <li class="nav-item">
    <a class="nav-link text-white h4" href="/juego/crear">Crear Preguntas</a>
  </li>
   <li class="nav-item">
    <a class="nav-link text-white h4" href="/juego/respuestas">Listado de Respuestas</a>
  </li>
</ul>
</nav>
<p class="h1 m-3" align="center">Listado de Preguntas</p>
{% block body %}
    <div class="row justify-content-md-center m-5">
        <div class="mb-3 col-lg-6">
                {% for pregunta in preguntas%}
                 <div class="alert alert-primary" role="alert">
                     {{pregunta}}
                <a class="btn btn-primary" href="{% url 'juego:detalle_pregunta' pregunta.pk %}">Detalle</a>
                <a class="btn btn-danger" href="{% url 'juego:eliminar' pregunta.pk %}">Eliminar</a>
                     <a class="btn btn-warning" href="{% url 'juego:editar' pregunta.pk %}">Editar</a>
                 </div>
                {% endfor %}
        </div>
     </div>
<div align="center"><a class="btn btn-success" href="/admin">Admin Django</a></div>
{% endblock %}